import { IPaginationParams } from "../../common/interfaces/common";
import { TUser } from "./user.model";

const getUsers = (params: IPaginationParams) => {
  // call getUsers from userRepository
  // ...
  // if error return Error (not found || invalid)
  // ...
  // else return userList
  // ...
};

const getOneUser = (userID: string) => {
  // call getOneUser from userRepository
  // ...
  // if error return Error (not found || invalid)
  // ...
  // else return user
  // ...
};

const createUser = (user: TUser) => {
  // call createOneUser from userRepository
  // ...
  // create user creation history
  // ...
  // if error return Error (not found || invalid)
  // ...
  // else return newUser
  // ...
};

const updateUser = (userID: string, user: TUser) => {
  // call updateOneUser from userRepository
  // ...
  // create user update history
  // ...
  // if error return Error (not found || invalid)
  // ...
  // else return updatedUser
  // ...
};

const deleteUser = (userID: string) => {
  // call deleteOneUser from userRepository
  // ...
  // create user delete history
  // ...
  // if error return Error (not found || invalid)
  // ...
  // else return deletedUser
  // ...
};

const searchUser = (searchText: string) => {
  // call findUser from userRepository
  // ...
  // create user search history
  // ...
  // if error return Error (not found || invalid)
  // ...
  // else return search results
  // ...
};

export { getUsers, getOneUser, createUser, updateUser, deleteUser, searchUser };
